# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='申请表类型')),
            ],
        ),
        migrations.CreateModel(
            name='BaseApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='流水单号')),
                ('form', models.TextField(max_length=16, verbose_name='表单摘要')),
                ('budget', models.IntegerField(verbose_name='金额')),
                ('currency_type', models.IntegerField(choices=[(1, '人民币'), (2, '美元')], default=1, verbose_name='货币类型')),
                ('coin_capital', models.CharField(blank=True, max_length=64, null=True, verbose_name='金额大写')),
                ('exigence', models.SmallIntegerField(choices=[(1, '紧急'), (2, '不紧急')], verbose_name='紧急程度')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='公司名称')),
                ('bank', models.CharField(max_length=32, verbose_name='账户银行')),
                ('card_num', models.CharField(max_length=32, verbose_name='银行卡号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '公司表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
            options={
                'verbose_name_plural': '部门表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('status', models.SmallIntegerField(choices=[(1, '已提交'), (2, '审核中'), (3, '未通过'), (4, '通过'), (5, '通过/已付款'), (6, '以归档')], verbose_name='状态')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='SecondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='申请表具体类型')),
                ('url', models.CharField(blank=True, max_length=32, null=True, verbose_name='url')),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ApplyType', verbose_name='所属大类')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('english_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='英文名')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('enroll_date', models.DateField(null=True, verbose_name='入职日期')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Department', verbose_name='部门')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Role', verbose_name='上司')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.User', verbose_name='账号')),
            ],
            options={
                'verbose_name_plural': '员工信息表',
            },
        ),
        migrations.CreateModel(
            name='ActivityApply',
            fields=[
                ('baseapply_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.BaseApply')),
                ('apply_name', models.CharField(default='推广活动申请表', editable=False, max_length=32, verbose_name='申请表名称')),
                ('product_name', models.CharField(max_length=64, verbose_name='推广产品名称')),
                ('product_version', models.CharField(max_length=64, verbose_name='推广产品版本')),
                ('advocate_platform', models.CharField(max_length=32, verbose_name='推广产品平台')),
                ('advocate_des', models.TextField(max_length=32, verbose_name='推广方案描述')),
                ('apply_cause', models.CharField(choices=[(1, '提升收入'), (2, '提升在玩'), (3, '增加注册'), (4, '其他')], default=None, max_length=32, verbose_name='申请原因')),
                ('anticipate', models.TextField(verbose_name='预期效果')),
                ('first_generalize', models.IntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='首次推广')),
                ('before_result', models.TextField(blank=True, null=True, verbose_name='以前效果描述')),
                ('buy_goods', models.IntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='需要申购物品')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='./upload/attachment/', verbose_name='上传附件')),
                ('note', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('apply_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.SecondType', verbose_name='申请表类型')),
            ],
            bases=('finance.baseapply',),
        ),
        migrations.AddField(
            model_name='record',
            name='apply_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BaseApply', verbose_name='流水号'),
        ),
        migrations.AddField(
            model_name='record',
            name='apply_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.SecondType', verbose_name='表单类型'),
        ),
        migrations.AddField(
            model_name='record',
            name='operate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.UserInfo', verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='baseapply',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='baseapply',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Company', verbose_name='付款公司'),
        ),
        migrations.AddField(
            model_name='baseapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.User', verbose_name='申请人'),
        ),
    ]
